[package]
name = "example"
version = "0.1.0"
edition = "2021"

[features]
default = ["jvm"]
jvm = []
uart = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inventory = "0.3.15"
